---
apiVersion: v1
kind: Pod
metadata:
  labels:
    agent: zeebe-ci-build
spec:
  nodeSelector:
    cloud.google.com/gke-nodepool: slaves
  containers:
    - name: maven
      image: maven:3.5-jdk-8
      command: ["cat"]
      # BLACK MAGIC
      # Elasticsearch cannot run as root but the official maven has only root.
      # For this reason we run this container with the same uid of the jenkins-slave image
      # In this way the jenkins user will run the command instead of root
      securityContext:
        runAsUser: 10000
      tty: true
      env:
        - name: LIMITS_CPU
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: JAVA_TOOL_OPTIONS
          value: |
            -XX:+UnlockExperimentalVMOptions
            -XX:+UseCGroupMemoryLimitForHeap
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 4
          memory: 16Gi
    - name: maven-it
      image: maven:3.5-jdk-8
      command: ["cat"]
      tty: true
      env:
        - name: LIMITS_CPU
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: JAVA_TOOL_OPTIONS
          value: |
            -XX:+UnlockExperimentalVMOptions
            -XX:+UseCGroupMemoryLimitForHeap
      resources:
        limits:
          cpu: 8
          memory: 16Gi
        requests:
          cpu: 4
          memory: 8Gi
    - name: golang
      image: golang:1.11.2
      command: ["cat"]
      tty: true
      resources:
        limits:
          cpu: 1
          memory: 8Gi
        requests:
          cpu: 1
          memory: 2Gi
